### ISSUE TITLE
Mapa

### ISSUE THREAD

**Issue by mmania** [hackerspace-silesia/calendar-oswiecim#103]
W momencie dodawania wydarzenie - dodanie lokalizacji na mapie nie działa.

**Comment by Fisiu** [comment]
Powiązane: https://github.com/MarkusH/django-osm-field/issues/15

**Comment by galuszkak** [comment]
@mmania po aktualizacji powinno działać z nową wersją django-osm-field. @Fisiu testowałem dzisiaj i działa mi lokalnie po podniesieniu django-osm-field do wersji tutaj wydanej https://github.com/MarkusH/django-osm-field/pull/23
