### ISSUE TITLE
Upgrade Django

### ISSUE THREAD

**Issue by galuszkak** [hackerspace-silesia/calendar-oswiecim#105]
Przydałoby się podnieść wersję Django. :)

**Comment by kardhen** [comment]
Nic nie podnoście błagam, bo się wysypie, a teraz nie ma tam tego kto ratować :)

**Comment by galuszkak** [comment]
@kardhen dlatego trzeba też zrobić #106 ;)

**Comment by kardhen** [comment]
@galuszkak - ok - teraz widzę :)

**Comment by galuszkak** [comment]
@kardhen wziąłem się za ten temat.

**Comment by galuszkak** [comment]
@kardhen aktualizacja zrobiona. Testowałem lokalnie powinno śmigać.
