### ISSUE TITLE
Popsuty bootstrap grid na stronie głównej

### ISSUE THREAD

**Issue by Fisiu** [hackerspace-silesia/calendar-oswiecim#18]
Aktualnie wszystkie wydarzenia na stronie głównej są wpakowane w jeden wiersz i chyba przez to układ wygląda źle. 

```html
<div class="row">
    <div class="col-xx-x">wydarzenie</div>
    <div class="col-xx-x">wydarzenie</div>
    (...)
    <div class="col-xx-x">wydarzenie</div>
    <div class="col-xx-x">wydarzenie</div>
</div>
```

A tak to wygląda w rzeczywistości.
![zrzut ekranu z 2015-07-29 o 12 38 20](https://cloud.githubusercontent.com/assets/33876/8955640/dde7c370-35ee-11e5-8ce5-18365520d38e.png)

Czy zrobienie 3 x <div class="row"> i w każdym z nich umieścić 3 wydarzenia jest dobrym pomysłem na rozwiązanie tego problemu?

**Comment by galuszkak** [comment]
Fixed
