### ISSUE TITLE
Kategorie wydarzeń

### ISSUE THREAD

**Issue by Fisiu** [hackerspace-silesia/calendar-oswiecim#21]
Możliwość przypisania kategorii do wydarzenia. Możliwość wyboru koloru dla kategorii. Wydarzenia na głównej oraz w kalendarzu używają kolorów kategorii. Możliwość filtrowania wydarzeń w kalendarzu po grupie.

**Comment by Palid** [comment]
@galuszkak daj znac jak trzeba bedzie jakis front klepnac do tego.

**Comment by firemark** [comment]
Czy to jest gotowe?

**Comment by Fisiu** [comment]
Kategorie są, działają. Póki co zamykam ;-)
