### ISSUE TITLE
Aktualne wydarzenia

### ISSUE THREAD

**Issue by Fisiu** [hackerspace-silesia/calendar-oswiecim#23]
Podejście drugie do kalendarza :-)

Aktualnie nadal korzystamy ze [starego kalendarza](http://kalendarz.oiloswiecim.pl/), ale wystawiłem wydarzenia w jsonie - co by łatwiej się je importowało (przynajmniej na czas poprawek kalendarza).

Tylko GET i HEAD ;-)
api: http://kalendarz.oiloswiecim.pl/api/index.php
wydarzenia: http://kalendarz.oiloswiecim.pl/api/index.php/mycal_events
wydarzenie x: http://kalendarz.oiloswiecim.pl/api/index.php/mycal_events/event_id/#

**Comment by firemark** [comment]
Hej, ja pisałem scrapera do tej starej api - nie będzie mi się chciało ściągać wydarzeń inaczej jak już to mam napisane :-)

**Comment by Fisiu** [comment]
No problem. A jak owym scraperem zaciągnąć aktualny zestaw danych i nakarmić nimi bazę kalendarza?

**Comment by kl-cruz** [comment]
Hm, Czy to jest zgodne z webdav'em?


Karol Lasończyk
starosta roku oraz spec. ISP
SSM Inf sem 3
wydział AEiI

W dniu 22 października 2015 16:03 użytkownik Marek Piechula <
notifications@github.com> napisał:

**Comment by galuszkak** [comment]
@Fisiu scrapper jest tutaj:
https://github.com/hackerspace-silesia/calendar-oswiecim/tree/master/scrapper
