### ISSUE TITLE
Edycja/Usuwanie własnych wydarzeń.

### ISSUE THREAD

**Issue by Fisiu** [hackerspace-silesia/calendar-oswiecim#24]
Jeśli user (nie mający żadnych dodatkowych uprawnień, czyli jest "Aktywny" i nie będący "W zespole") doda wydarzenie, aktualnie nie ma możliwości edytowania czy usunięcia. tego wydarzenia.
Z kolei jak dodam usera do zespołu i dodam mu uprawnienia np. do edycji wydarzeń ('calendars|event|Can change event') to z poziomu panelu admina, ten user może edytować wszystkie wydarzenia - zamiast tylko swoich.

Najlepiej żaby jednak taki user bez dostępu do /admin/ miał możliwość edycji i usuwania ale tylko i wyłącznie swoich wydarzeń.

**Comment by kardhen** [comment]
To jest prawie zrobione :) do końca tygodnia powinno się udać - tak @firemark ? :)

**Comment by galuszkak** [comment]
@kardhen po czym wnosisz? ;) Bo ja się za to zabrałem w weekend mam nadzieję, ze nie dubluje pracy z firemarkiem...

**Comment by firemark** [comment]
Oh. Nie zauważyłem - nie patrzyłem w kod admina :P
Ja wykorzystuje stary kod z widoków do edycji bo ktoś brutalnie skasował link [edytuj] - pewnie kiedy kalendarz powstał to nie było miejsca na linka :P

Ps. Punkty (mapkę) kasujemy - według Anii są niepotrzebne.

**Comment by firemark** [comment]
Oh. Nie zauważyłem - nie patrzyłem w kod admina :P
Ja wykorzystuje stary kod z widoków do edycji bo ktoś brutalnie skasował link [edytuj] - pewnie kiedy kalendarz powstał to nie było miejsca na linka :P

Ps. Punkty (mapkę) kasujemy - według Anii są niepotrzebne.

**Comment by firemark** [comment]
Oh. Nie zauważyłem - nie patrzyłem w kod admina :P
Ja wykorzystuje stary kod z widoków do edycji bo ktoś brutalnie skasował link [edytuj] - pewnie kiedy kalendarz powstał to nie było miejsca na linka :P

Ps. Punkty (mapkę) kasujemy - według Anii są niepotrzebne.

**Comment by Fisiu** [comment]
Aktualnie, jeśli user ma uprawnienia do `calendars | event | Can {add,edit,delete} event` to otwierając konkretne wydarzenie dostaję błąd widoczny poniżej. Jeśli user nie jest zalogowany bądź jest zalogowany jako admin, to błąd nie występuje. 

```python
Environment:


Request Method: GET
Request URL: http://localhost:8000/wydarzenie/141/

Django Version: 1.8.3
Python Version: 3.4.1
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.gis',
 'calendars',
 'sorl.thumbnail',
 'ckeditor',
 'widget_tweaks',
 'datetimewidget')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware')


Traceback:
File "/home/fisiu/Devel/virtualenv/calendar/lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/fisiu/Devel/virtualenv/calendar/lib/python3.4/site-packages/django/views/generic/base.py" in view
  71.             return self.dispatch(request, *args, **kwargs)
File "/home/fisiu/Devel/virtualenv/calendar/lib/python3.4/site-packages/django/views/generic/base.py" in dispatch
  89.         return handler(request, *args, **kwargs)
File "/home/fisiu/Devel/virtualenv/calendar/lib/python3.4/site-packages/django/views/generic/detail.py" in get
  116.         context = self.get_context_data(object=self.object)
File "/home/fisiu/Devel/github/calendar-oswiecim/webapp/calendars/views.py" in get_context_data
  61.         context['can_edit'] = self.has_access(self.request.user, 'change')[0]
File "/home/fisiu/Devel/github/calendar-oswiecim/webapp/calendars/mixins.py" in has_access
  35.         return obj.user.pk == user.pk, False

Exception Type: AttributeError at /wydarzenie/141/
Exception Value: 'NoneType' object has no attribute 'pk'
```

**Comment by firemark** [comment]
Ok, widzę błąd - załozyłem, że user zawsze będzie ustawiony, a to błąd :-)

**Comment by firemark** [comment]
Done - popraiwłem inne bugi (problem z dziedziczeniem :P)

**Comment by galuszkak** [comment]
@firemark @kardhen a Pull Request i code review? :)

**Comment by firemark** [comment]
Myślałem że sam siedzę w projekcie narazie :D sorry

**Comment by kardhen** [comment]
@galuszkak no powiedzieli, że mogę zamknąć, to zamknęłam :D pardon - otworzyłam i sobie teraz sami zamykajcie :P

**Comment by firemark** [comment]
to ja zamknę :P
