### ISSUE TITLE
Wiele kategorii dla wydarzenia

### ISSUE THREAD

**Issue by Fisiu** [hackerspace-silesia/calendar-oswiecim#25]
Aktualna implementacja kategorii pozwala na dodanie tylko jednej kategorii do wydarzenie. Jednak nie jest to wystarczające.

**Comment by galuszkak** [comment]
@Fisiu  :P smucisz mnie tym, akurat to pytanie zadałem chyba z 2 razy :P jak braliśmy się za implementację tego :). Ale spoko poprawimy. Możliwe, że w weekend to ruszę. :+1:

**Comment by Fisiu** [comment]
@galuszkak Projekt żyje wiec i wymagania się zmieniają ;-)

**Comment by galuszkak** [comment]
:dancer: that's great :)

**Comment by firemark** [comment]
dodaję obrazek: http://wstaw.org/m/2015/11/21/hidden.png

**Comment by Fisiu** [comment]
@firemark Kiedy będą pokazywać się wydarzenia zakończone na głównej?

@mmania Widok kategorii ładny, tylko nie wiem czy chcemy widzieć te zakończone?

**Comment by firemark** [comment]
@Fisiu Gdy wyświetlały się same nowe to nie było w sumie wiadomo co i jak które są do czego. Teraz widać że coś się dzieje :-). Kiedy? Kiedy minie czas rozpoczęcia zdarzenia. Chyba że chcemy dodać 'w trakcie'

**Comment by kardhen** [comment]
@Fisiu ja bym to zostawiła - fajnie wygląda, widać, że coś się dzieje i jest jakaś archiwizacja :)

**Comment by Fisiu** [comment]
@firemark @kardhen Ale strona główna ma statyczny widok - w sensie 12 najbliższych, więc jak to ma wyświetlać minione(zakończone) wydarzenia? Nie mamy tam nawigacji.
Poza tym, wydarzenie teraz nie są posortowane wg. najbliższych:
![Uploading calendar_home_2015-11-21_21.58.53.png…]()

**Comment by kardhen** [comment]
@Fisiu ale jakby się zdarzyło tak, że nie będzie więcej 12 nowych? to lepiej wyszarzyć chyba, żeby się nie myliło...

**Comment by Fisiu** [comment]
@kardhen Jeśli nie będzie nowych, to faktycznie, niech zakończone się wyświetlają. 

Jednak i tak pozostaje jeszcze kwesta sortowania :)

**Comment by Fisiu** [comment]
@firemark Jak posortować teraz te wydarzenia na głównej?

**Comment by firemark** [comment]
w views.py jest HomeView i tam jest warunek z sortowaniem.
Do queryset jest dokumentacja: https://docs.djangoproject.com/en/1.8/ref/models/querysets/

**Comment by Fisiu** [comment]
Co prawda 
```python
Event.objects.filter(start_time__gte=datetime.datetime.now()).order_by('start_time')[:12]
```
przywróci sortowanie, ale ficzer z minionymi wydarzeniami przestanie działać bo w `context['events']` będą zawsze wydarzenia `> dt_now`.

**Comment by galuszkak** [comment]
To zostawmy order_by wywalcie warunek i dodajmy wyszarzanie dla starszych niz dzisiaj. @Fisiu czy tak jest ok? To mogę to zrobić.

**Comment by Fisiu** [comment]
@galuszkak Co w aktualnej implementacji jest nie teges? Wiele kategorii można przypisać do wydarzenia i reszta działa tak jak powinna. W sumie to powinienem zamknąć to zgłoszenie :D

**Comment by galuszkak** [comment]
@Fisiu odnoszę się do ostatniego komentarza na temat minionych wydarzeń ;). Ale jeżeli to zrobione to zamykaj ;).

**Comment by Fisiu** [comment]
@galuszkak FYI #53.
