### ISSUE TITLE
Eksport wydarzeń

### ISSUE THREAD

**Issue by Fisiu** [hackerspace-silesia/calendar-oswiecim#26]
Funkcjonalność eksportowania wydarzeń, np na podstawie organizatora i kategorii.

**Comment by firemark** [comment]
Może jeszcze frytki do tego? :-)
Większy opis - do czego eksport - xml, csv? rss?

**Comment by galuszkak** [comment]
@Fisiu eksport do czego? CSV? iCal? JSON? XML? To jest kompletnie nie zrozumiałe dla mnie ;). Może bardziej use case do czego to potrzebne...

**Comment by Fisiu** [comment]
Frytki bez soli :D
Myślę, że eksport do ical wystarczy, tak aby user mógł podpiąć tego icala do np. swojego kalendarza.

**Comment by firemark** [comment]
https://github.com/hackerspace-silesia/calendar-oswiecim/pull/33 jest ok?

**Comment by firemark** [comment]
@Fisiu hm? :P

**Comment by Fisiu** [comment]
@firemark Wygląda dobrze, tylko ta strefa czasowa ;-) 
```python
timezone = 'Europe/Warsaw'
```
 Czy tam utc+1.

**Comment by Fisiu** [comment]
@kardhen Czy u Ciebie czas też jest prawidłowy? Jeśli tak, to można zamknąć.

**Comment by kardhen** [comment]
@Fisiu jeśli chodzi Ci o czas na nicnic, to u mnie jest ok :) można zamknąć :)

**Comment by Fisiu** [comment]
W związku z powyższym, zamykam.
