### ISSUE TITLE
Porzucenie django.contrib.gis*

### ISSUE THREAD

**Issue by Fisiu** [hackerspace-silesia/calendar-oswiecim#28]
Skoro nie używamy mapy (i współrzędnych, które były źle rysowane - pomimo wprowadzenia współ. X były rysowane Y) to może warto byłoby porzucić wszystkie geo-zależności typu: `django.contrib.gis*`?

**Comment by galuszkak** [comment]
+1

**Comment by Fisiu** [comment]
Zdaje się, że #32 powinien rozwiązać ten problem.
