### ISSUE TITLE
Obrazki przez formularz $HOST/wydarzenie/dodaj/ nie są przesyłane

### ISSUE THREAD

**Issue by Fisiu** [hackerspace-silesia/calendar-oswiecim#30]
Jeśli admin dodaje wydarzenie przez menu administracyjne, wówczas wszystkie pola formularza są przesyłane prawidłowo. Z kolei gdy korzystamy z formularza `$HOST/wydarzenie/dodaj/` po wypełnieniu pól i wskazaniu obrazka/plakatu - przesyłane są wszystkie pola z wyjątkiem obrazka. W efekcie naszego wydarzenie zostaje utworzone bez plakatu...

**Comment by firemark** [comment]
Hmm… Dziwne. W bazie jest pusty url?

**Comment by Fisiu** [comment]
Pole `image` w tabeli `calendars_event ` jest puste.

**Comment by firemark** [comment]
https://github.com/hackerspace-silesia/calendar-oswiecim/pull/34 
u mnie działa :-)

**Comment by Fisiu** [comment]
U mnie też. Zamykam.
