### ISSUE TITLE
Godziny

### ISSUE THREAD

**Issue by mmania** [hackerspace-silesia/calendar-oswiecim#35]
Godzina z kalendarza nie zgadza się z informacjami zawartmi w formularzu. Problem ze strefami czasowymi?

**Comment by Fisiu** [comment]
Np. mamy na liście wydarzeń 21 listopada 2015 wydarzenie
`08:30 - 10:45 SOBOTA W MDK`
po jego kliknięciu widzimy zaś godzinę rozpoczęcia `09:30`.
