### ISSUE TITLE
Widok "Dzień"

### ISSUE THREAD

**Issue by mmania** [hackerspace-silesia/calendar-oswiecim#37]
Zmienić wygląd "Dnia" z listy, na widok przypominający funkcjonujący teraz kalendarz: http://kalendarz.oiloswiecim.pl/
Widać, które wydarzenia się zazębiają i ile trwają.
Bardziej czytelne i estetyczne

**Comment by Fisiu** [comment]
@mmania Czy tak to może wyglądać? https://github.com/hackerspace-silesia/calendar-oswiecim/pull/50#issuecomment-159106215

**Comment by mmania** [comment]
Pięknie
