### ISSUE TITLE
Niebieskie tło wydarzeń

### ISSUE THREAD

**Issue by mmania** [hackerspace-silesia/calendar-oswiecim#40]
Zostawić tylko przy aktualnym dniu (we wszystkich widokach) - dzięki czemu dzień dzisiejszy będzie się bardzieć wyróżniać.

**Comment by Fisiu** [comment]
@mmania Zrobione w #56. Możesz zamknąć ;-)

**Comment by mmania** [comment]
od biedy mogę zaakceptować ;)
