### ISSUE TITLE
Typo! w widoku admina

### ISSUE THREAD

**Issue by Fisiu** [hackerspace-silesia/calendar-oswiecim#45]
Nic pilnego ale boli.
![categorys](https://cloud.githubusercontent.com/assets/33876/11320475/713e666a-9099-11e5-8dfb-018ecf78ce74.png)

**Comment by firemark** [comment]
wystarczy dać plurar_name w class Meta
Jak dla mnie brzmi zajebiście, dlatego zostawiłem :D
